version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "javascript"
    directory: "/web"
    update_schedule: "live"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "ruby:bundler"
    directory: "/docs"
    update_schedule: "live"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "docker"
    directory: "/internal/suites/example/compose/authelia"
    update_schedule: "daily"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "docker"
    directory: "/internal/suites/example/compose/haproxy"
    update_schedule: "daily"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "docker"
    directory: "/internal/suites/example/compose/duo-api"
    update_schedule: "daily"
    commit_message:
      prefix: "[MISC] "
      include_scope: true
  - package_manager: "docker"
    directory: "/internal/suites/example/compose/kind"
    update_schedule: "daily"
    commit_message:
      prefix: "[MISC] "
      include_scope: true